name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - run: ruby -c Casks/rootie.rb
      - run: brew tap hmbakhsh/tap "$GITHUB_WORKSPACE"
      - run: brew trust --cask hmbakhsh/tap/rootie
      - run: brew audit --cask --strict hmbakhsh/tap/rootie
